name: bharatvalidator
description: >-
  🇮🇳 India-first Flutter form validation package with 30+ validators.
  Covers Aadhaar, PAN, GST, IFSC, UPI, Driving License, Passport, Voter ID etc.
version: 1.0.2
homepage: https://github.com/flutterbysunny/bharatvalidator
repository: https://github.com/flutterbysunny/bharatvalidator
issue_tracker: https://github.com/flutterbysunny/bharatvalidator/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: